services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: "2gb"

  yahoo_news:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: yahoo_news
    volumes:
      - type: bind
        source: /home/kjqw/university/.cache
        target: /workspace/.cache
      - type: bind
        source: ../
        target: /workspace/yahoo_news
      - type: bind
        source: /home/kjqw/.gitconfig
        target: /workspace/.gitconfig
      - type: bind
        source: /home/kjqw/.ssh
        target: /workspace/.ssh
      - type: bind
        source: /home/kjqw/university/B4/references
        target: /workspace/references
    depends_on:
      - selenium
    working_dir: /workspace
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [ gpu ]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    #   - HF_HOME=/workspace/.cache/huggingface
    command: sleep infinity
