services:
  yahoo-news-comment-scraper:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: yahoo-news-comment-scraper
    volumes:
      # LLMのモデルを保存する場所を source: に指定すると、コンテナを消してもそこにダウンロードしたモデルが残る
      # 別のコンテナで同じモデルを使いたい場合に便利
      # - type: bind
      #   source: /home/kjqw/university/.cache
      #   target: /workspace/.cache
      - type: bind
        source: ../
        target: /workspace/yahoo-news-comment-scraper
    depends_on:
      - selenium
      - postgresql_db
    working_dir: /workspace
    # コンテナ内でGPUを使う場合は以下の設定を追加する
    # NVIDIA Container Toolkitをインストールしていないと使えない
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [ gpu ]
    # environment:
    #   - HF_HOME=/workspace/.cache/huggingface # これはtransformersライブラリがモデルを保存したり読み込んだりするディレクトリを指定するための環境変数。GPUの設定とは無関係
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    command: sleep infinity

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: "2gb"

  postgresql_db:
    image: postgres:16.4
    container_name: postgresql_db
    environment:
      POSTGRES_USER: kjqw
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: yahoo_news
    ports:
      - "5432:5432"
    shm_size: "2gb"
    volumes:
      - type: bind
        source: ../db_data
        target: /var/lib/postgresql/data
